version: "3.1"

services:
  me2_first:
    build:
      context: .
    image: me2
    container_name: me2_first
    networks:
      me2devnet:
    ports:
      - "127.0.0.1:5690:5683/udp"
    volumes:
      - ./config/docker_me_conf.yaml:/usr/src/app/me.yaml
      - ./pime2:/usr/src/app/pime2
    cap_add:
      - net_raw
      - net_admin

  me2_second:
    build:
      context: .
    image: me2
    container_name: me2_second
    networks:
      me2devnet:
    ports:
      - "127.0.0.1:5691:5683/udp"
    volumes:
      - ./config/docker_me_conf2.yaml:/usr/src/app/me.yaml
    cap_add:
      - net_raw
      - net_admin

#  me2_third:
#    build:
#      context: .
#    image: me2
#    container_name: me2_third
#    networks:
#      me2devnet:
#    ports:
#      - "5692:5683"
#    volumes:
#      - ./config/docker_me_conf2.yaml:/usr/src/app/me.yaml
#    cap_add:
#      - net_raw
#      - net_admin

networks:
  me2devnet:
