@startuml

' this is a comment
' read here for syntax: https://plantuml.com/sequence-diagram

title 1. Process:
footer Forschungsprojekt 2022, IPVS
scale 3

actor User #blue
participant "PIME\nCoAp-Server" as PCS

== 1.1 Process 1 ==

User -> PCS: Do something
activate PCS

deactivate PCS

'== Run process 1.1 ==
@enduml