@startuml

' this is a comment
' read here for syntax: https://plantuml.com/sequence-diagram

title ME2: Flow Execution
footer Forschungsprojekt 2022, IPVS
scale 2


actor System #blue

participant "router_loop()" as RL
participant "FlowManager" as FM
== 1.2 New FlowMessage  ==
activate RL

System -> RL: Do something
System -> RL: New message arrives
activate RL
RL -> FM: Pass to FlowManager:\nhandle_flow_message(FlowMessage)
activate FM
FM -> FM: If valid:\nexecute_flow(FlowMessage)
FM -> RL:
deactivate FM
deactivate RL
RL -> System: finish


@enduml