@startuml

' this is a comment
' read here for syntax: https://plantuml.com/sequence-diagram

title TEMPLATE! 1. Process:
footer Forschungsprojekt 2022, IPVS
scale 2

actor System #blue
participant "PIME\nCoAp-Server" as PCS

== 1.1 New Sensor-Read-Message on (internal) queue  ==

User -> PCS: Do something
activate PCS

deactivate PCS

'== Run process 1.1 ==
@enduml