instance_id: 111111111
loglevel: DEBUG
database: me2.db
is_debug: true
host: 0.0.0.0
port: 5683
read_interval: 5.0
sensors:
  - name: "Temperature-Sensor"
    type: temperature
    gpio1: 12
    is_test_mode: true