instance_id: 123456678
loglevel: DEBUG
is_debug: false
host: 127.0.0.1
port: 5683
read_interval: 5.0
sensors:
  - name: "Button-Sensor"
    type: button
    pin1: 12
    pin2: 13
    is_test_mode: true